- name: mariadb10のインストール
  apt:
    name: ['mariadb-server-10.1','mariadb-client-10.1','python3-mysqldb']
    state: present

- name: mysqlサービス起動
  service:
    name: mysql
    state: started

- name: mysqlデーモンの自動起動設定済みかを確認
  shell: grep "sudo service mysql start" "{{ profile }}"
  register: mysql_check
  failed_when: mysql_check.rc not in [0, 1]
  changed_when: false

- name: mysqlデーモンの自動起動設定
  blockinfile:
    dest: "{{ profile }}"
    insertafter: EOF          # ファイルの末尾に追加
    marker: ""                # 追加部分を示すマーカー(空行)
    block: |
      # mysql start
      if ! sudo service mysql status > /dev/null 2>&1 ; then
          sudo service mysql start > /dev/null 2>&1
      fi
  when: mysql_check.rc == 1

- name: 環境設定ファイルの再読み込みが必要(環境設定ファイル変更時)★
  debug:
    msg: source "{{ profile }}"

- name: DB作成
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: DBユーザの作成
  no_log: true
  mysql_user:
    host: localhost
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: "{{ db_name }}.*:ALL,GRANT"
    state: present
