- name: mariadb10のインストール
  become_user: root
  apt:
    name: ['mariadb-server-10.1','mariadb-client-10.1','python-mysqldb']
    state: present

- name: mysqlサービス起動
  become_user: root
  service:
    name: mysql
    state: started

- name: mysqlデーモンの自動起動設定済みかを確認
  shell: grep "sudo service mysql start" "{{ profile }}"
  register: mysql_check
  failed_when: mysql_check.rc not in [0, 1]
  changed_when: false

- name: mysqlデーモンの自動起動設定
  blockinfile:
    dest: "{{ profile }}"
    insertafter: EOF          # ファイルの末尾に追加
    marker: ""                # 追加部分を示すマーカー(空行)
    block: |
      # mysql start
      if ! service mysql status > /dev/null 2>&1 ; then
          sudo service mysql start > /dev/null 2>&1
      fi
  when: mysql_check.rc == 1

- name: MySQL DB作成
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: MySQLユーザの作成
  mysql_user:
    host: localhost
    name: "{{ db_username }}"
    password: "{{ db_userpass }}"
    priv: "{{ db_name }}.*:ALL,GRANT"
    state: present
